### ISSUE TITLE
Testing against rails versions with Combustion?

### ISSUE THREAD

**Issue by pboling** [mailpace/mailpace-rails#28]
Just read the blog post here:
https://blog.mailpace.com/blog/testing-rails-gems/

Wondering if combustion was considered, and if so, why it wasn't chosen. I am currently deciding between doing it the way this gem does it or using combustion, in my gem `sanitize_email` (which, as an aside, would actually be a good solution for people needing to test their integration with your service in their live environment without risking test emails going to customers, and which just had a bug report for a bug that only occurs with a specific version of rails which my tests missed, just like in your blog post). Thanks!

**Comment by pboling** [comment]
I was able to get it working.

Working example of Appraisal & Combustion with a massive test matrix on Github Actions in my sanitize_email gem here: https://github.com/pboling/sanitize_email/commit/a9c1d9a11732b57e1b898e74516bbff36724ff97

* Ruby 2.3 - Ruby 3.3
* Rails 3.0 - Rails 7.1
* bundler 1 & bundler 2

I really love your solution as well, but I ended up using off the shelf parts, since I was starting with an old Appraisal install from the Travis-CI days.

**Comment by paul-oms** [comment]
Thanks for this! I actually wasn't aware of these Gems which is why I went with the CircleCI approach. I think your way looks better, but I'm not planning to update this gem to match, purely due to inertia.
